#!/bin/bash
venv_path="venv"
search_dir="$1"
adj_dir="../adj/"
node_feat_dir="../node_feats/"

if [ ! -d "$search_dir" ]; then
  echo "Directory does not exist: $search_dir"
  exit 1
fi

if [ ! -d "$venv_path" ]; then
  echo "Virtual env path does not exist: $venv_path"
  exit 1
fi

if [ -f "../$(basename "$0").log" ]; then
  echo "Removing old log file ../$(basename "$0").log"
  rm "../$(basename "$0").log"
fi

if [ ! -d "$adj_dir" ]; then
  echo "${adj_dir} does not exist...creating"
  mkdir "$adj_dir"
fi

if [ ! -d "$node_feat_dir" ]; then
  echo "${node_feat_dir} does not exist...creating"
  mkdir "$node_feat_dir"
fi

source "${venv_path}/bin/activate"

echo $(ls "$search_dir" | wc -l) "files to process"

for folder in $(ls "$search_dir"); do
  full_path="${search_dir}${folder}"
  if [ -d "$full_path" ]; then
    base="$(basename "$full_path")"
    echo -n "${base}..."
    if [ ! -f "${adj_dir}${base}.npz" ] && [ ! -f "${node_feat_dir}${base}.csv" ]; then
      # run the python script for generating the tree
      python3 src/codebase_parser.py \
        --dir "$full_path" \
        --nf "${node_feat_dir}${base}" \
        --adj "${adj_dir}${base}" \
        --dim "$2" >> "../$(basename "$0").log"
      echo "Done"
    else
      echo "Skipping (exists)"
    fi
  fi
done

echo "Done generating all trees."
echo "Log file generated: ../$(basename "$0").log"